### ISSUE TITLE
加载模型的时候报错

### ISSUE THREAD

**Issue by qin1201** [equationl/paddleocr4android#26]
加载模型的时候报错E/paddle: onFaildlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~vUQmPS6cgjFaV3KC29OdGQ==/car.bkrc.com.car2022-xjIkcZuxy6z3jSDntEFL7A==/base.apk!/lib/armeabi-v7a/libpaddle_full_api_shared.so"...这是什么问题呢

**Comment by equationl** [comment]
你好，请问是运行 demo 报错还是集成到您的项目中报错？

如果是集成到您的项目中报错，方便提供一下最下复现 demo 吗？

**Comment by viclm** [comment]
同问，集成到项目运行到arm64的手机上报错，本地模拟器没问题

**Comment by equationl** [comment]
@viclm 报错信息是什么

**Comment by viclm** [comment]
--------- beginning of crash
--------- beginning of system
2024-07-22 09:34:24.951  1698-1698  StorageManagerService   pid-1698                             V  Package com.equationl.paddleocr4android.app does not have legacy storage
--------- beginning of main
2024-07-22 09:49:21.582  4034-4598  imgdec                  pid-4034                             I  OCRVersionString 1.6.5.22
2024-07-22 09:49:31.717  6513-6513  PaddleOCRPlugin         uni.liuming.demo                     E  模型加载失败: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~aVc-MZsPlomRkdbRkPvBfA==/uni.liuming.demo-ssl4xw1jXF8pIn6_YeeHWQ==/lib/arm64/libpaddle_full_api_shared.so"...
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~aVc-MZsPlomRkdbRkPvBfA==/uni.liuming.demo-ssl4xw1jXF8pIn6_YeeHWQ==/lib/arm64/libpaddle_full_api_shared.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at com.baidu.paddle.fastdeploy.FastDeployInitializer.init(FastDeployInitializer.java:19)
                                                                                                    	at com.baidu.paddle.fastdeploy.pipeline.PPOCRBase.<clinit>(PPOCRBase.java:176)
                                                                                                    	at com.equationl.fastdeployocr.OCR.initModel(OCR.kt:240)
                                                                                                    	at com.equationl.fastdeployocr.OCR.initModelSync-IoAF18A(OCR.kt:79)
                                                                                                    	at com.equationl.fastdeployocr.OCR$initModel$1.invokeSuspend(OCR.kt:96)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-07-22 09:56:01.701  4621-6256  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.720  4621-6256  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.740  4621-6344  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.761  4621-6344  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.780  4621-6344  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.799  4621-6188  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.820  4621-6188  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.838  4621-6344  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.863  4621-6188  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.884  4621-6188  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.917  4621-6188  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.933  4621-6344  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.952  4621-6188  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.974  4621-6344  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload
2024-07-22 09:56:01.992  4621-6188  RegisteredApis          pid-4621                             W  Api =ro.config.device.gpiocradle is either not present or not lazyload

**Comment by viclm** [comment]
安卓11报的错，安卓10没问题

**Comment by equationl** [comment]
@viclm NDK 版本兼容问题，参考：

https://github.com/facebook/react-native/issues/41238

https://blog.csdn.net/bby85/article/details/125449862

**Comment by viclm** [comment]
我指定了和你一样的 ndkVersion '21.1.6352462' 还是不行

**Comment by equationl** [comment]
方便的话你发一个最小复现 demo 完整的项目给我，我试一下

**Comment by equationl** [comment]
你这个不是原生安卓项目吧？

**Comment by viclm** [comment]
https://github.com/viclm/UniPlugin-Hello-AS

下面的操作录屏文件


https://github.com/user-attachments/assets/946e92f6-d16e-4d4a-adac-a628bb990c73

**Comment by equationl** [comment]
就是 NDK 版本兼容问题，因为这里是直接引用的 xx.so 文件而没有实时编译，所以你通过 `ndkVersion '24.0.8215888'` 指定 NDK 版本是没用的。

由于安卓特性，不能有同名文件，所以你在 gardle 脚本中使用了配置 `pickFirst 'lib/arm64-v8a/libc++_shared.so'` 这导致会优先使用 app 模块的文件而非其他模块文件，换句话说就是 paddlerocr 可用的 `libc++_shared.so` 被替换成了你的项目生成的 `libc++_shared.so` 文件，但是这个文件不兼容 paddleocr。

因此，你有两个解决办法：

1. 修改你的项目构建选项，使其能够使用 paddleocr 的 `libc++_shared.so` 或 将你的项目编译生成的 `libc++_shared.so` 改为和 paddleocr 兼容的版本。
2. 强制替换项目的 `libc++_shared.so` 为兼容的 `libc++_shared.so` 文件，如图：

![image](https://github.com/user-attachments/assets/86a31ff9-20e8-4245-8356-77a568e50f5f)

下面这个视频是使用 方法2 修改后的效果：

https://github.com/user-attachments/assets/27255ede-2c78-4d5a-a327-611505a670ab

**Comment by xieshun908** [comment]
你好，我运行demo的时候加载模型失败：
<img width="450" alt="1" src="https://github.com/user-attachments/assets/d7610910-96c6-4d47-a8d3-86078dabf02d">

**Comment by equationl** [comment]
@xieshun908 不支持 x86_64

**Comment by xieshun908** [comment]
我用的雷电模拟器，要换真机吗？不好意思，我是新手，麻烦教下。

**Comment by equationl** [comment]
雷电模拟器可以指定运行APP的架构，请自行搜索或咨询模拟器客服
